name: Test action

on:
  workflow_dispatch:
    inputs:
      file:
        description: 'Run single file. Input example: "scenario.test.js" or "scenario.test" without quotes'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JWT: ${{secrets.JWT}}

    steps:
      - uses: actions/checkout@v2
      - run: npm install -g mocha dotenv
      - name: append 'test/' folder to the file name
        run: echo "file=test/${{inputs.file}}" >> $GITHUB_ENV
      - run: npm i
        working-directory: ./tests/test
      - run: npm run all-reporter ${{ inputs.file && env.file || '' }}
        working-directory: ./tests/test
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: 'https://hooks.slack.com/services/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'
          SLACK_TITLE: 'Job finished'
          SLACK_MESSAGE: ${{env.TMP_URL}}
          CUSTOM: "Custom text"