name: Test action

on:
  workflow_dispatch:
    inputs:
      file:
        description: 'Run single or multiple files. Input example: scenario.test.js, source.test.js'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JWT: ${{secrets.JWT}}

    steps:
      - uses: actions/checkout@v2
      - run: npm install -g mocha dotenv
      - run: echo "file=test/${{inputs.file}}" >> $GITHUB_ENV
      - run: npm i
        working-directory: ./tests
      #- run: npm run all-reporter ${{ inputs.file && 'test/', inputs.file || '' }}
      - run: npm run all-reporter ${{ inputs.file && env.file || '' }}
        working-directory: ./tests