name: Test action

on:
  workflow_dispatch:
    inputs:
      file:
        description: 'Run single file. Input example: "scenario.test.js" or "scenario.test" without quotes'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JWT: ${{secrets.JWT}}

    steps:
      - uses: actions/checkout@v2
      - run: npm install -g mocha dotenv
      - name: append 'test/' folder to the file name
        run: echo "file=test/${{inputs.file}}" >> $GITHUB_ENV
      - run: npm i
        working-directory: ./tests/test
      - run: npm run all-reporter ${{ inputs.file && env.file || '' }}
        working-directory: ./tests/test
      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: 'https://hooks.slack.com/services/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'
          SLACK_TITLE: 'Job finished'
          SLACK_MESSAGE: 'https://github.com/okryvorotko/github-actions/actions/runs/'${{GITHUB_RUN_ID}}
          MSG_MINIMAL: true
          SLACK_USERNAME: github