name: Caller
on:
  workflow_dispatch:
    inputs:
      someInput:
        type: string
        description: 'Input string example'
jobs:
  run_reusable:
    uses: ./.github/workflows/reusable.yml
    env:
      someInput: github.event.inputs.someInput || "reusable"
  run_reusable2:
    uses: ./.github/workflows/reusable2.yml
    env:
      someInput: github.event.inputs.someInput || "reusable2"
