name: Reusable
on:
  workflow_dispatch:
    inputs:
      someInput:
        type: boolean
        description: 'Input boolean example'
        required: true
        default: false
jobs:
  run_tests:
    uses: ./.github/workflows/reusable.yml
