name: Caller1
on:
  workflow_dispatch:

jobs:
  preparations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create file
        id: create-file
        run: |
          echo "some shared variable value: caller1" > filename
          FILE_CONTENT=$(cat filename)
          echo "FROM_CALLER_TO_REUSABLE=$FILE_CONTENT" >> $GITHUB_OUTPUT
    outputs:
      FROM_CALLER_TO_REUSABLE: ${{ steps.create-file.outputs.FROM_CALLER_TO_REUSABLE }}


  run_reusable:
    needs: preparations
    uses: ./.github/workflows/reusable.yml
    with:
      command: npm run reusable1
      someInput: Input from Caller1
      FROM_CALLER_TO_REUSABLE: ${{needs.preparations.outputs.FROM_CALLER_TO_REUSABLE}}

  post:
    needs: run_reusable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm i
      - run: npm install -g mocha dotenv

      - name: Post tests
        run: npm run postTests
        env:
          FROM_REUSABLE_TO_CALLER: ${{ needs.run_reusable.outputs.FROM_REUSABLE_TO_CALLER }}
