name: Caller
on:
  workflow_dispatch:
    inputs:
      someInput:
        type: string
        description: 'Input string example'
jobs:
  run_reusable:
    uses: ./.github/workflows/reusable.yml
  run_reusable2:
    uses: ./.github/workflows/reusable2.yml
