name: Caller2
on:
  workflow_dispatch:
    inputs:
      someInput:
        type: string
        description: Input string example
jobs:
  run_reusable:
    uses: ./.github/workflows/reusable.yml
    with:
      command: npm run reusable2
      someInput: Input from Caller2
