name: Reusable
on:
  workflow_call:
    inputs:
      someInput:
        type: boolean
        description: 'Input boolean example'
        required: true
        default: false
jobs:
  uses: .github/workflows/reusable.yml
