name: Caller1
on:
  workflow_dispatch:

jobs:
  run_reusable:
    runs-on: ubuntu-latest
    steps:
    - name: print something
      run: echo 'print something'
    - name: run reusable
      uses: ./.github/workflows/reusable.yml
      with:
        command: npm run reusable1
        someInput: Input from Caller1
    - name: print something
      run: echo 'print something'
