name: Caller1
on:
  workflow_dispatch:

jobs:
  preparations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create file
        run: |
          echo "file content" > filename
          FILE_CONTENT=$(cat filename.txt)
          echo "GITHUB_VAR=$FILE_CONTENT" >> $GITHUB_ENV

  run_reusable:
    needs: preparations
    uses: ./.github/workflows/reusable.yml
    with:
      command: npm run reusable1
      someInput: Input from Caller1
      FILE: {{ env.GITHUB_VAR }}

  post:
    needs: run_reusable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Delete file
        run: rm -rf filename
