name: Caller1
on:
  workflow_dispatch:

jobs:
  preparations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create file
        id: create-file
        run: |
          echo "some shared variable value: caller1" > filename
          FILE_CONTENT=$(cat filename)
          echo "SHARED_VAR=$FILE_CONTENT" >> $GITHUB_OUTPUT
    outputs:
      SHARED_VAR: ${{ steps.create-file.outputs.SHARED_VAR }}


  run_reusable:
    needs: preparations
    id: reusable-job
    uses: ./.github/workflows/reusable.yml
    with:
      command: |
        npm run reusable1
        echo "some nested shared variable value: reusable" > nested
        FILE_CONTENT=$(cat nested)
        echo "NESTED_VAR=$FILE_CONTENT" >> $GITHUB_OUTPUT
      someInput: Input from Caller1
      sharedVar: ${{needs.preparations.outputs.SHARED_VAR}}
    outputs:
      NESTED_VAR: ${{ reusable-job.outputs.NESTED_VAR }}

  post:
    needs: run_reusable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Print nested
        run: echo "$nestedVar"
        with:
          nestedVar: ${{ needs.run_reusable.outputs.NESTED_VAR }}
