name: Check if file exists

on:
  workflow_dispatch:

jobs:
  check-file-exists:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create file
        run: echo "file content" > filename.txt

      - name: Check if exists
        run: |
          if [ -f filename.txt ]; then isExists=true; fi
          (test -f filename.txt && isExists=true) || isExists=false
          echo $isExists
          if [ $isExists -e "true" ]; then
            FILE_CONTENT=$(cat filename.txt);
            echo "GITHUB_VAR=$FILE_CONTENT" >> $GITHUB_ENV;
          else
            echo 'file does not exist'
          fi
      - name: Print var
        run: echo ${{ env.GITHUB_VAR }}
