name: Check if file exists

on:
  workflow_dispatch:

jobs:
  check-file-exists:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create file
        run: echo "file content" > filename.txt

      - name: Check if exists
        run: |
          if [ -f filename.txt ]; then
            FILE_CONTENT=$(cat filename.txt);
            echo "GITHUB_VAR=$FILE_CONTENT" >> $GITHUB_ENV;
          else
            echo 'file does not exist'
          fi
      - name: Check if exists (for the file that doesn't)
        run: |
          if [ -f nonExistingFile ]; then
            FILE_CONTENT=$(cat nonExistingFile);
            echo "GITHUB_VAR2=$FILE_CONTENT" >> $GITHUB_ENV;
          else
            echo 'file does not exist'
          fi
      - name: Print var
        run: echo ${{ env.GITHUB_VAR }}
      - name: Print var for non existing file
        run: echo ${{ env.GITHUB_VAR2 }}
