name: Pass variables between steps

on:
  workflow_dispatch:

jobs:
  pass-variables-between-steps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Step 1
        continue-on-error: true
        run: |
          exit 1
          echo "STEP_STATUS=SUCCEEDED" >> $GITHUB_ENV
        shell: bash

      - name: Step 2
        if: failure()
        run: echo "STEP_STATUS=FAILED" >> $GITHUB_ENV

      - name: Step 3
        run: |
          echo "The status of Step 1 was: ${{ env.STEP_STATUS || 'FAILURE' }}"
        shell: bash
