name: Pass variables between steps

on:
  push:
    branches:
      - pass-variables-between-steps

jobs:
  pass-variables-between-steps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Step 1
        id: step1
        continue-on-error: true
        run: |
          exit 1
          echo "STEP_STATUS=SUCCEEDED" >> $GITHUB_ENV

      - name: Step 2
        run: |
          echo "The status of Step 1 was: ${{ env.STEP_STATUS || 'FAILURE' }}"

      - name: Step 3
        if: failure()
        run: echo 'Alert! Step 1 failed'
