name: Pass variables between steps

on:
  workflow_dispatch:

jobs:
  print-branch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Step 1
        continue-on-error: true
        run: |
          echo "STEP_STATUS=FAILED" >> $GITHUB_ENV
          exit 1
        shell: bash

      - name: Step 2
        run: |
          echo "The status of Step 1 was: ${{ env.STEP_STATUS }}"
        shell: bash
