name: Print inputs

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        type: boolean
        description: 'Logging on tests execution'
        required: true
        default: false
      slackNotify:
        type: boolean
        description: 'Send slack notification to #nightlytest on failure'
        required: true
        default: false
      testrail:
        type: boolean
        description: 'TestRail'
        required: true
        default: true
  pull_request:
    types: [ opened, reopened ]

jobs:
  print-branch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Inputs
        run: echo "${{ toJson(github.event.inputs) || toJSON(env) }}"
      
