name: Print branch

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, reopened ]

jobs:
  print-branch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: npm i
      - run: npm run printBranch
        env:
          HEAD_REF: ${{github.head_ref}}
