name: Print inputs

on:
  workflow_dispatch:
    inputs:
      input1:
        default: 'input1'
      input2:
        type: boolean
        default: false
      input3:
        type: choice
        default: 'default'
        options:
          - choice1
          - choice2
          - choice3
  pull_request:
    types: [ opened, reopened ]

jobs:
  print-inputs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Inputs
        if: ${{ github.event.inputs }}
        run: echo "${{ toJson(github.event.inputs) }}"
