name: Print secrets

on:
  workflow_dispatch:

jobs:
  print-inputs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Print secret
        run: |
          echo "${{ secrets.PASSWORD }}" > password
          cat password
