name: Print secrets

on:
  workflow_dispatch:

jobs:
  print-secrets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Print secret
        run: |
          echo secrets.PASSWORD
          echo ${{secrets.PASSWORD}} | sed 's/./& /g'
          echo secrets.USERNAME
          echo ${{secrets.USERNAME}} | sed 's/./& /g'

