name: Reusable
on:
  workflow_call:
    inputs:
      command:
        type: string
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: npm i
      - run: npm install -g mocha dotenv

      - name: tests
        id: tests
        run: ${{inputs.command}}
        env:
          someInput: inputs.someInput