name: Reusable
on:
  workflow_call:
    inputs:
      command:
        type: string
      someInput:
        type: string
      from-caller-to-reusable:
        type: string
    outputs:
      FROM_REUSABLE_TO_CALLER:
        value: ${{ jobs.tests.outputs.FROM_REUSABLE_TO_CALLER }}
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: npm i
      - run: npm install -g mocha dotenv

      - name: tests
        id: tests
        run: |
          ${{inputs.command}}
          echo "file content" > filename.txt
          FILE_CONTENT=$(cat filename.txt)
          echo "FROM_REUSABLE_TO_CALLER=$FILE_CONTENT" >> $GITHUB_OUTPUT
        env:
          someInput: ${{inputs.someInput}}
          from-caller-to-reusable: ${{inputs.from-caller-to-reusable}}

    outputs:
      FROM_REUSABLE_TO_CALLER: ${{ steps.tests.outputs.FROM_REUSABLE_TO_CALLER }}
