name: Reusable2
on:
  workflow_call:
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: npm i
      - run: npm install -g mocha dotenv

      - name: tests
        id: tests
        run: npm run reusable2
        env:
          someInput: inputs.someInput
