name: Reusable
on:
  workflow_call:
    inputs:
      someInput:
        type: boolean
        description: 'Input boolean example'
        required: true
        default: false
jobs:
  run_tests:
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: npm install -g mocha dotenv

      - name: tests
        id: tests
        run: npm run test
