name: Reusable
on:
  workflow_call:
    inputs:
      command:
        type: string
      someInput:
        type: string
      sharedVar:
        type: string
    outputs:
      nestedVar: ${{ steps.tests.outputs.nestedVar }}
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: npm i
      - run: npm install -g mocha dotenv

      - name: tests
        id: tests
        run: |
          ${{inputs.command}}
          echo "file content" > filename.txt
          FILE_CONTENT=$(cat filename.txt)
          echo "nestedVar=$FILE_CONTENT" >> $GITHUB_OUTPUT
        env:
          someInput: ${{inputs.someInput}}
          sharedVar: ${{inputs.sharedVar}}

    outputs:
      nestedVar: steps.tests.outputs.nestedVar
