name: Reusable
on:
  workflow_call:
    inputs:
      someInput:
        type: string
        description: 'Input string example'
jobs:
  run_tests:
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: npm install -g mocha dotenv

      - name: tests
        id: tests
        run: npm run test
