name: Contexts

on:
  workflow_dispatch:
    pull_request:
      types: [ ready_for_review ]

jobs:
  print-branch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: npm i
