name: Skip tests

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      runTests:
        type: boolean
        description: Run tests
        default: true

jobs:
  skip-step:
    runs-on: ubuntu-latest
    env:
      runTests: true

    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: echo "Running tests"
        if: (inputs.runTests || env.runTests) == true

      - name: Last step
        run: echo "Last step"
