name: Skip step based on input

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      runStep:
        type: boolean
        description: Run step
        default: false

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      runStep: true

    steps:
      - uses: actions/checkout@v3

      - name: Print envs
        run:
          |
          echo "github.event_name ${{github.event_name}}"
          echo "github.event.inputs.runStep ${{github.event.inputs.runStep}}"

      - name: Conditional step
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.runStep == true || github.event_name == 'schedule' }}
        run: echo "Step is executed"