name: Skip tests if failure

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      slackNotify:
        type: boolean
        description: Slack notification
        default: true

jobs:
  skip-step:
    runs-on: ubuntu-latest
    env:
      slackNotify: true

    steps:
      - uses: actions/checkout@v3

      - name: Failing step
        run: echo "Success"

      - name: Run tests
        run: |
          echo "Running tests"
          echo "env.slackNotify: ${{env.slackNotify}}"
          echo "inputs.slackNotify: ${{inputs.slackNotify}}"
          echo "github.event_name: ${{github.event_name}}"
          echo "inputs.slackNotify || github.slackNotify == 'schedule': ${{inputs.slackNotify || github.event_name == 'schedule'}}"
        if: ${{failure() && (inputs.slackNotify || github.event_name == 'schedule') && env.slackNotify}}


