name: Skip tests

on:
  workflow_dispatch:
    inputs:
      runTests:
        type: boolean
        description: Run tests
        default: true

jobs:
  skip-step:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: echo "Running tests"
        if: github.event.inputs.runTests == true

      - name: Last step
        run: echo "Last step"
